### ISSUE TITLE
Fix: Pre-commit workflow failing due to phantom file in cache

### ISSUE THREAD

**Issue by sabothra** [CloudSmith-Agent-Benchmark/sqlfluff#521]
## Root Cause
The pre-commit workflow is failing because it's trying to check a file `test/core/helpers/mock_test.py` that no longer exists in the repository, but is still referenced in the pre-commit cache or temporary files. The workflow is running with `--all-files` which picks up cached versions of the file.

## Mitigation Steps
1. Add `pre-commit clean` command to the workflow to clear the cache before running the hooks
2. Keep the `--files-to-exclude="test/core/helpers/mock_test.py"` parameter to explicitly exclude the phantom file

```yaml
# Modified workflow step
- name: Run pre-commit hooks
  run: |
    set -o pipefail
    # Clean pre-commit cache to remove phantom files
    pre-commit clean
    pre-commit gc
    # Run pre-commit on all files, excluding the phantom file
    pre-commit run --show-diff-on-failure --color=always --all-files --files-to-exclude="test/core/helpers/mock_test.py" | tee ${RAW_LOG}
```

## PR Link
No PR created

## Validation Results
**Status:** Failed
